// open ending: door-open
// happy: laugh
// sad: sad-cry
// love interest fulfilled: heart or heart_broken
// to early to judge: arrow-right
export const endings = {
    'Ship of Magic': { overall: 'arrow-right' },
    "Assassin's Quest": { overall: 'cloud-sun', love_interest: 'heart_broken' },
    'Royal Assassin': { overall: 'arrow-right' },
    "Assassin's Apprentice": { overall: 'arrow-right' },
    'Tipping the Velvet': {
        overall: 'sun',
        loveInterest: 'heart',
        notes: "Love interest changes quite drastically at the end but I'd like to think it ended with the best one.",
    },
    "The Places I've Cried in Public": { overall: 'sun' },
    'Thinking, Fast and Slow': { overall: 'tba' },
    '...And a Happy New Year?': { overall: 'tba' },
    'A Head Full of Ghosts': { overall: 'tba' },
    'We Have Always Lived in the Castle': { overall: 'tba' },
    Alone: { overall: 'tba' },
    Alight: { overall: 'tba' },
    Alive: { overall: 'tba' },
    "What's a Girl Gotta Do?": { overall: 'tba' },
    'How Hard Can Love Be?': { overall: 'tba' },
    'Am I Normal Yet?': { overall: 'cloud-sun', loveInterest: 'door-open' },
    'If It Bleeds': { overall: 'tba' },
    'Resistance is Futile': { overall: 'tba' },
    'Coffin, Scarcely Used': { overall: 'tba' },
    "I'm Thinking of Ending Things": { overall: 'tba' },
    Gingerbread: { overall: 'tba' },
    'The Tailor': { overall: 'tba' },
    'Taskmaster: 220 Extraordinary Tasks for Ordinary People': { overall: 'tba' },
    'King of Scars': { overall: 'tba' },
    'Crooked Kingdom': { overall: 'tba' },
    'Six of Crows': { overall: 'tba' },
    'Ruin and Rising': { overall: 'tba' },
    'Siege and Storm': { overall: 'tba' },
    'Shadow and Bone': { overall: 'tba' },
    'The Ten Thousand Doors of January': { overall: 'tba' },
    'Sons of Destiny': { overall: 'tba' },
    '500 Miles from You': { overall: 'tba' },
    'Lord of the Shadows': { overall: 'tba' },
    'The Lake of Souls': { overall: 'tba' },
    'Killers of the Dawn': { overall: 'tba' },
    'Allies of the Night': { overall: 'tba' },
    'The Vampire Prince': { overall: 'tba' },
    'Hunters of the Dusk': { overall: 'tba' },
    'The Colored Museum': { overall: 'tba' },
    'Trials of Death': { overall: 'tba' },
    'Vampire Mountain': { overall: 'tba' },
    'Tunnels of Blood': { overall: 'tba' },
    "The Vampire's Assistant": { overall: 'tba' },
    'A Living Nightmare': { overall: 'tba' },
    'Red, White & Royal Blue': { overall: 'tba' },
    'The Flatshare': { overall: 'tba' },
    'The Signature of All Things': { overall: 'tba' },
    'Eat, Pray, Love': { overall: 'tba' },
    'The Endless Beach': { overall: 'tba' },
    'The Cafe by the Sea': { overall: 'tba' },
    'We Are Okay': { overall: 'tba' },
    'The Bookish Life of Nina Hill': { overall: 'tba' },
    'The Unhoneymooners': { overall: 'tba' },
    Verity: { overall: 'tba' },
    'Consent: A Memoir of Unwanted Attention': { overall: 'tba' },
    'Do You Mind If I Cancel?': { overall: 'tba' },
    'Dear Girls: Intimate Tales, Untold Secrets, & Advice for Living Your Best Life': { overall: 'tba' },
    'The Invited': { overall: 'tba' },
    'The Institute': { overall: 'tba' },
    'The Unhoneymooners': { overall: 'tba' },
    'City of Girls': { overall: 'tba' },
    'My Sister, the Serial Killer': { overall: 'tba' },
    'The Swallows': { overall: 'tba' },
    'Ninth House': { overall: 'tba' },
    'Fl\u00fcsternde H\u00e4nde': { overall: 'tba' },
    'Blanca & Roja': { overall: 'tba' },
    'Little Women': { overall: 'tba' },
    'Marriage and other Games': { overall: 'tba' },
    'The Birthday Party': { overall: 'tba' },
    'An Eligible Bachelor': { overall: 'tba' },
    'The Forever House': { overall: 'tba' },
    'A Night on the Orient Express': { overall: 'tba' },
    'The Long Weekend': { overall: 'tba' },
    'Christmas at the Beach Hut': { overall: 'tba' },
    'The Beach Hut Next Door': { overall: 'tba' },
    'How to Find Love in a Bookshop': { overall: 'tba' },
    'The Beach Hut': { overall: 'tba' },
    'The Haunting of Hill House': { overall: 'tba' },
    'The Bookshop on the Shore': { overall: 'tba' },
    'The Stone Sky': { overall: 'tba' },
    'The Obelisk Gate': { overall: 'tba' },
    'The Ocean at the End of the Lane': { overall: 'tba' },
    'Three Women': { overall: 'tba' },
    "Lilith's Brood": { overall: 'tba' },
    'The Mermaid': { overall: 'tba' },
    'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch': { overall: 'tba' },
    'The Seven Husbands of Evelyn Hugo': { overall: 'tba' },
    'One True Loves': { overall: 'tba' },
    'Maybe in Another Life': { overall: 'tba' },
    'The Long Way to a Small, Angry Planet': { overall: 'tba' },
    'House of Salt and Sorrows': { overall: 'tba' },
    'The Fates Divide': { overall: 'tba' },
    "Ender's Game": { overall: 'tba' },
    Allegiant: { overall: 'tba' },
    'Carve the Mark': { overall: 'tba' },
    'Run Away': { overall: 'tba' },
    'The Mother-in-Law': { overall: 'tba' },
    'Mystery Man': { overall: 'tba' },
    'The Silent Patient': { overall: 'tba' },
    'Daisy Jones & The Six': { overall: 'tba' },
    'The Mother-in-Law': { overall: 'tba' },
    Uprooted: { overall: 'tba' },
    Recursion: { overall: 'tba' },
    'The Beauty': { overall: 'tba' },
    'Lost Boy: The True Story of Captain Hook': { overall: 'tba' },
    'The Girl in Red': { overall: 'tba' },
    'Gods of Jade and Shadow': { overall: 'tba' },
    'Nine Perfect Strangers': { overall: 'tba' },
    'The Hookup': { overall: 'tba' },
    'All Our Wrong Todays': { overall: 'tba' },
    'The Bone Clocks': { overall: 'tba' },
    'The Merry Spinster: Tales of Everyday Horror': { overall: 'tba' },
    'True North: Discover Your Authentic Leadership': { overall: 'tba' },
    'The Great Alone': { overall: 'tba' },
    'The Fifth Season': { overall: 'tba' },
    'Not That Bad: Dispatches from Rape Culture': { overall: 'tba' },
    'The Great Alone': { overall: 'tba' },
    'Run Away': { overall: 'tba' },
    'Trust Exercise': { overall: 'tba' },
    'The Great Believers': { overall: 'tba' },
    "I Was Told There'd Be Cake: Essays": { overall: 'tba' },
    Queenie: { overall: 'tba' },
    'The Authentics': { overall: 'tba' },
    'The Vegetarian': { overall: 'tba' },
    'The Final Empire': { overall: 'tba' },
    'The Well of Ascension': { overall: 'tba' },
    'The Hero of Ages': { overall: 'tba' },
    'Words of Radiance': { overall: 'tba' },
    Oathbringer: { overall: 'tba' },
    'The Way of Kings': { overall: 'tba' },
    'On Beauty': { overall: 'tba' },
    'Roots: The Saga of an American Family': { overall: 'tba' },
    Faithful: { overall: 'tba' },
    'The Witch Elm': { overall: 'tba' },
    'The Marriage of Opposites': { overall: 'tba' },
    'The Broken Girls': { overall: 'tba' },
    Elevation: { overall: 'tba' },
    'The Hunger': { overall: 'tba' },
    'Red Clocks': { overall: 'tba' },
    'Baby Teeth': { overall: 'tba' },
    Sadie: { overall: 'tba' },
    'Sometimes I Lie': { overall: 'tba' },
    'The Outsider': { overall: 'tba' },
    'The Wife Between Us': { overall: 'tba' },
    'The Wedding Date': { overall: 'tba' },
    'The Museum of Extraordinary Things': { overall: 'tba' },
    'Practical Magic': { overall: 'tba' },
    'Matchmaking for Beginners': { overall: 'tba' },
    'An Excess Male': { overall: 'tba' },
    'The Terror': { overall: 'tba' },
    'The Rules of Magic': { overall: 'tba' },
    'Sharp Objects': { overall: 'tba' },
    'The Song of Achilles': { overall: 'tba' },
    Galatea: { overall: 'tba' },
    'A Separation': { overall: 'tba' },
    Ilium: { overall: 'tba' },
    'The Woman in the Window': { overall: 'tba' },
    'The Paying Guests': { overall: 'tba' },
    'An American Marriage': { overall: 'tba' },
    'How to Be a Woman': { overall: 'tba' },
    Horrorstör: { overall: 'tba' },
    'Losing It': { overall: 'tba' },
    'How to Build a Girl': { overall: 'tba' },
    'Force of Nature': { overall: 'tba' },
    'The Three-Body Problem': { overall: 'tba' },
    Educated: { overall: 'tba' },
    'The Astonishing Color of After': { overall: 'tba' },
    Circe: { overall: 'tba' },
    'The Grip of It': { overall: 'tba' },
    'The Girl Before': { overall: 'tba' },
    'Rabbit Cake': { overall: 'tba' },
    Borne: { overall: 'tba' },
    'The Power': { overall: 'tba' },
    Mischling: { overall: 'tba' },
    Chemistry: { overall: 'tba' },
    'Hello From the Gillespies': { overall: 'tba' },
    'Left Neglected': { overall: 'tba' },
    'The Mist': { overall: 'tba' },
    'Magpie Murders': { overall: 'tba' },
    'Saving Grace': { overall: 'tba' },
    'A Thousand Acres': { overall: 'tba' },
    'Some Luck': { overall: 'tba' },
    'All Grown Up': { overall: 'tba' },
    'After I Do': { overall: 'tba' },
    'All In': { overall: 'tba' },
    'One of Us Is Lying': { overall: 'tba' },
    'Killer Instinct': { overall: 'tba' },
    'The Naturals': { overall: 'tba' },
    'Sleeping Beauties': { overall: 'tba' },
    'Into the Water': { overall: 'tba' },
    'Little Fires Everywhere': { overall: 'tba' },
    'Almost Midnight': { overall: 'tba' },
    'The Atlas of Love': { overall: 'tba' },
    'Goodbye for Now': { overall: 'tba' },
    'This Is How It Always Is': { overall: 'tba' },
    'My Not So Perfect Life': { overall: 'tba' },
    'The City & the City': { overall: 'tba' },
    'Version Control': { overall: 'tba' },
    'Station Eleven': { overall: 'tba' },
    'Carry On': { overall: 'tba' },
    'The Bookshop on the Corner': { overall: 'tba' },
    'We Love You, Charlie Freeman': { overall: 'tba' },
    Sweetbitter: { overall: 'tba' },
    'The Great American Whatever': { overall: 'tba' },
    'Art Girls Are Easy': { overall: 'tba' },
    'Beauty Queens': { overall: 'tba' },
    'Thirteen Reasons Why': { overall: 'tba' },
    'Ready Player One': { overall: 'tba' },
    'We Eat Our Own': { overall: 'tba' },
    'Eleanor Oliphant Is Completely Fine': { overall: 'tba' },
    'La Belle Sauvage': { overall: 'tba' },
    'The Wangs vs. the World': { overall: 'tba' },
    'Lucy and Linh': { overall: 'tba' },
    'The Hating Game': { overall: 'tba' },
    'Dark Matter': { overall: 'tba' },
    'Exit, Pursued by a Bear': { overall: 'tba' },
    Crosstalk: { overall: 'tba' },
    'American Gods': { overall: 'tba' },
    Moonglow: { overall: 'tba' },
    'The Wishing Game': { overall: 'tba' },
    Lolita: { overall: 'tba' },
    Lolita: { overall: 'tba' },
    'We Need to Talk About Kevin': { overall: 'tba' },
    'The Natural Way of Things': { overall: 'tba' },
    'The Dry': { overall: 'tba' },
    'Holidays on Ice': { overall: 'tba' },
    'The Idiot': { overall: 'tba' },
    'A Wizard of Earthsea': { overall: 'tba' },
    'Harry Potter and the Cursed Child: Parts One and Two': { overall: 'tba' },
    'The Color of Magic': { overall: 'tba' },
    'Dreams of Gods and Monsters': { overall: 'tba' },
    'Night of Cake & Puppets': { overall: 'tba' },
    'In a Dark, Dark Wood': { overall: 'tba' },
    'I Had a Nice Time And Other Lies...: How to find love  sh*t like that': { overall: 'tba' },
    'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life': { overall: 'tba' },
    'The Fireman': { overall: 'tba' },
    "He's Just Not That Into You: The No-Excuses Truth to Understanding Guys": { overall: 'tba' },
    "My Best Friend's Exorcism": { overall: 'tba' },
    'Marked in Flesh': { overall: 'tba' },
    'All the Birds in the Sky': { overall: 'tba' },
    'Behind Closed Doors': { overall: 'tba' },
    'Lilac Girls': { overall: 'tba' },
    'Eligible: A Modern Retelling of Pride & Prejudice': { overall: 'tba' },
    'Small Great Things': { overall: 'tba' },
    'The Nest': { overall: 'tba' },
    'Black Iris': { overall: 'tba' },
    'Buffering: Unshared Tales of a Life Fully Loaded': { overall: 'tba' },
    'Cam Girl': { overall: 'tba' },
    Burned: { overall: 'tba' },
    Faefever: { overall: 'tba' },
    Dreamfever: { overall: 'tba' },
    Shadowfever: { overall: 'tba' },
    Bloodfever: { overall: 'tba' },
    Darkfever: { overall: 'tba' },
    'The Amazing Adventures of Kavalier & Clay': { overall: 'tba' },
    'Truly Madly Guilty': { overall: 'tba' },
    'All the Light We Cannot See': { overall: 'tba' },
    'A Gathering of Shadows': { overall: 'tba' },
    'Days of Blood & Starlight': { overall: 'tba' },
    'Daughter of Smoke & Bone': { overall: 'tba' },
    'In Her Shoes': { overall: 'tba' },
    Fangirl: { overall: 'tba' },
    'The Help': { overall: 'tba' },
    'Can You Keep a Secret?': { overall: 'tba' },
    'A Darker Shade of Magic': { overall: 'tba' },
    'Remember Me?': { overall: 'tba' },
    'The Undomestic Goddess': { overall: 'tba' },
    'Finding Audrey': { overall: 'tba' },
    'Summer at Little Beach Street Bakery': { overall: 'tba' },
    'On Tour': { overall: 'tba' },
    'The Royal We': { overall: 'tba' },
    'What Alice Forgot': { overall: 'tba' },
    "The Husband's Secret": { overall: 'tba' },
    'Dangerous Girls': { overall: 'tba' },
    Darkfever: { overall: 'tba' },
    'Dangerous Boys': { overall: 'tba' },
    'Twilight / Life and Death': { overall: 'tba' },
    'This Song Will Save Your Life': { overall: 'tba' },
    'Red Queen': { overall: 'tba' },
    Alice: { overall: 'tba' },
    'On Tour': { overall: 'tba' },
    Binge: { overall: 'tba' },
    'Why Not Me?': { overall: 'tba' },
    'Everything, Everything': { overall: 'tba' },
    'Simon vs. the Homo Sapiens Agenda': { overall: 'tba' },
    'Circus Mirandus': { overall: 'tba' },
    'The Girl on the Train': { overall: 'tba' },
    'Watashitachi no Shiawase na Jikan': { overall: 'tba' },
    'Royal Wedding': { overall: 'tba' },
    'Valentine Princess': { overall: 'tba' },
    'Sweet Sixteen Princess': { overall: 'tba' },
    'The Princess Present': { overall: 'tba' },
    'Blackout. Morgen ist es zu sp\u00e4t': { overall: 'tba' },
    'The Martian': { overall: 'tba' },
    Specials: { overall: 'tba' },
    Pretties: { overall: 'tba' },
    Uglies: { overall: 'tba' },
    "The Time Traveler's Wife": { overall: 'tba' },
    'The Running Man': { overall: 'tba' },
    Next: { overall: 'tba' },
    'Beautiful Bastard': { overall: 'tba' },
    'Beautiful Player': { overall: 'tba' },
    'Beautiful Stranger': { overall: 'tba' },
    'The Master Magician': { overall: 'tba' },
    'The Glass Magician': { overall: 'tba' },
    'The Paper Magician': { overall: 'tba' },
    'The Good Girl': { overall: 'tba' },
    Silence: { overall: 'tba' },
    Crescendo: { overall: 'tba' },
    'Molly Moon Stops the World': { overall: 'tba' },
    "Molly Moon's Incredible Book of Hypnotism": { overall: 'tba' },
    'Me and Earl and the Dying Girl': { overall: 'tba' },
    'Church of Marvels': { overall: 'tba' },
    'The Fault in Our Pants': { overall: 'tba' },
    'On Grace:First Edition': { overall: 'tba' },
    'The Night We Said Yes': { overall: 'tba' },
    'Eleanor & Park': { overall: 'tba' },
    'The Fault in Our Stars': { overall: 'tba' },
    'Girl Online': { overall: 'tba' },
    'Biedermann und die Brandstifter': { overall: 'tba' },
    'Hush, Hush': { overall: 'tba' },
    'Achtung, Zeitfalle!': { overall: 'tba' },
    'Level 4 \u2013 Die Stadt der Kinder': { overall: 'tba' },
    'The Strange and Beautiful Sorrows of Ava Lavender': { overall: 'tba' },
    Opposition: { overall: 'tba' },
    Origin: { overall: 'tba' },
    Opal: { overall: 'tba' },
    Onyx: { overall: 'tba' },
    Obsidian: { overall: 'tba' },
    'Mr. Mercedes': { overall: 'tba' },
    Landline: { overall: 'tba' },
    'A Discovery of Witches': { overall: 'tba' },
    'Vision in Silver': { overall: 'tba' },
    'Written in Red': { overall: 'tba' },
    'Murder of Crows': { overall: 'tba' },
    'The Thousand-Dollar Tan Line': { overall: 'tba' },
    'The Enchanted': { overall: 'tba' },
    'Big Little Lies': { overall: 'tba' },
    Panic: { overall: 'tba' },
    "To All the Boys I've Loved Before": { overall: 'tba' },
    'We Were Liars': { overall: 'tba' },
    'Never Have I Ever: My Life (So Far) Without a Date': { overall: 'tba' },
    'Yes Please': { overall: 'tba' },
    'Away Laughing on a Fast Camel': { overall: 'tba' },
    'Then He Ate My Boy Entrancers': { overall: 'tba' },
    'Dancing in My Nuddy-Pants': { overall: 'tba' },
    "On the Bright Side, I'm Now the Girlfriend of a Sex God": { overall: 'tba' },
    'Knocked Out by My Nunga-Nungas': { overall: 'tba' },
    'The Sky Is Everywhere': { overall: 'tba' },
    'The Hunger Games': { overall: 'tba' },
    "Amanda's Wedding": { overall: 'tba' },
    'The Loveliest Chocolate Shop in Paris': { overall: 'tba' },
    'Little Beach Street Bakery': { overall: 'tba' },
    'Christmas at the Cupcake Caf\u00e9': { overall: 'tba' },
    'Meet Me at the Cupcake Caf\u00e9': { overall: 'tba' },
    'Christmas at Rosie Hopkins\u2019 Sweetshop': { overall: 'tba' },
    "Welcome to Rosie Hopkins' Sweet Shop of Dreams": { overall: 'tba' },
    'The Fine Art of Pretending': { overall: 'tba' },
    'The Darkest Part of the Forest': { overall: 'tba' },
    Jackaby: { overall: 'tba' },
    "I'll Give You the Sun": { overall: 'tba' },
    'The Death Cure': { overall: 'tba' },
    'The Scorch Trials': { overall: 'tba' },
    'The Maze Runner': { overall: 'tba' },
    'The Leftovers': { overall: 'tba' },
    "Breakfast with Tiffany: An Uncle's Memoir": { overall: 'tba' },
    'A Fractured Mind: My Life with Multiple Personality Disorder': { overall: 'tba' },
    'River of Blue Fire': { overall: 'tba' },
    'The Battle of the Labyrinth': { overall: 'tba' },
    'The Last Olympian': { overall: 'tba' },
    "The Titan's Curse": { overall: 'tba' },
    'The Sea of Monsters': { overall: 'tba' },
    'The Lightning Thief': { overall: 'tba' },
    'The Last Letter from Your Lover': { overall: 'tba' },
    'The One': { overall: 'tba' },
    'The Elite': { overall: 'tba' },
    'The Selection': { overall: 'tba' },
    'One Plus One': { overall: 'tba' },
    'Angus, Thongs and Full-Frontal Snogging': { overall: 'tba' },
    'The Hundred-Year-Old Man Who Climbed Out of the Window and Disappeared': { overall: 'tba' },
    'Me Before You': { overall: 'tba' },
    'The Unlikely Pilgrimage of Harold Fry': { overall: 'tba' },
    'The Storied Life of A.J. Fikry': { overall: 'tba' },
    "Ronia, the Robber's Daughter": { overall: 'tba' },
    'Mountain of Black Glass': { overall: 'tba' },
    'Sea of Silver Light': { overall: 'tba' },
    'City of Golden Shadow': { overall: 'tba' },
    'New Moon': { overall: 'tba' },
    'Breaking Dawn': { overall: 'tba' },
    Eclipse: { overall: 'tba' },
    'Sezon burz': { overall: 'tba' },
    'Pani Jeziora': { overall: 'tba' },
    'Wie\u017ca Jask\u00f3\u0142ki': { overall: 'tba' },
    'Chrzest ognia': { overall: 'tba' },
    'Czas pogardy': { overall: 'tba' },
    'Krew elf\u00f3w': { overall: 'tba' },
    'Miecz przeznaczenia': { overall: 'tba' },
    Sleep: { overall: 'tba' },
    'Before I Go to Sleep': { overall: 'tba' },
    'Last Sacrifice': { overall: 'tba' },
    'Spirit Bound': { overall: 'tba' },
    Frostbite: { overall: 'tba' },
    'Blood Promise': { overall: 'tba' },
    'Shadow Kiss': { overall: 'tba' },
    'Vampire Academy': { overall: 'tba' },
    Fearless: { overall: 'tba' },
    Reckless: { overall: 'tba' },
    Inkdeath: { overall: 'tba' },
    Inkspell: { overall: 'tba' },
    'The Subtle Knife': { overall: 'tba' },
    'Set This House in Order': { overall: 'tba' },
    'Fool on the Hill': { overall: 'tba' },
    'Bad Monkeys': { overall: 'tba' },
    'About a Boy': { overall: 'tba' },
    'A Long Way Down': { overall: 'tba' },
    'High Fidelity': { overall: 'tba' },
    Inheritance: { overall: 'tba' },
    Brisingr: { overall: 'tba' },
    Eldest: { overall: 'tba' },
    Hidden: { overall: 'tba' },
    Destined: { overall: 'tba' },
    Awakened: { overall: 'tba' },
    Burned: { overall: 'tba' },
    Tempted: { overall: 'tba' },
    Hunted: { overall: 'tba' },
    Chosen: { overall: 'tba' },
    Untamed: { overall: 'tba' },
    Betrayed: { overall: 'tba' },
    Marked: { overall: 'tba' },
    'The Awakening': { overall: 'tba' },
    "Po's Story": { overall: 'tba' },
    'The Kin': { overall: 'tba' },
    "Suth's Story": { overall: 'tba' },
    "Noli's Story": { overall: 'tba' },
    'The Plains of Passage': { overall: 'tba' },
    'The Mammoth Hunters': { overall: 'tba' },
    'The Valley of Horses': { overall: 'tba' },
    'The Clan of the Cave Bear': { overall: 'tba' },
    'The Struggle': { overall: 'tba' },
    'Bridget Jones: The Edge of Reason': { overall: 'tba' },
    "Bridget Jones's Diary": { overall: 'tba' },
    'Lone Wolf': { overall: 'tba' },
    "Angela's Ashes": { overall: 'tba' },
    'The Donor': { overall: 'tba' },
    'Fifty Shades Freed': { overall: 'tba' },
    'Fifty Shades Darker': { overall: 'tba' },
    'Fifty Shades of Grey': { overall: 'tba' },
    'Mansfield Park': { overall: 'tba' },
    'Sense and Sensibility': { overall: 'tba' },
    Frelseren: { overall: 'tba' },
    Phantom: { overall: 'tba' },
    Flaggermusmannen: { overall: 'tba' },
    Panserhjerte: { overall: 'tba' },
    Nemesis: { overall: 'tba' },
    "The Devil's Star": { overall: 'tba' },
    'The Redbreast': { overall: 'tba' },
    'The Snowman': { overall: 'tba' },
    'Happy Family': { overall: 'tba' },
    'Jesus liebt mich': { overall: 'tba' },
    'Mieses Karma': { overall: 'tba' },
    "Lamb: The Gospel According to Biff, Christ's Childhood Pal": { overall: 'tba' },
    'A Dance with Dragons': { overall: 'tba' },
    'A Feast for Crows': { overall: 'tba' },
    'A Storm of Swords': { overall: 'tba' },
    'The Pinhoe Egg': { overall: 'tba' },
    "Conrad's Fate": { overall: 'tba' },
    'Witch Week': { overall: 'tba' },
    'The Magicians of Caprona': { overall: 'tba' },
    'Charmed Life': { overall: 'tba' },
    'Castle in the Air': { overall: 'tba' },
    'The Lives of Christopher Chant': { overall: 'tba' },
    'The Tales of Beedle the Bard': { overall: 'tba' },
    'Harry Potter and the Order of the Phoenix': { overall: 'tba' },
    'Harry Potter and the Half-Blood Prince': { overall: 'tba' },
    'Harry Potter and the Goblet of Fire': { overall: 'tba' },
    'The Amber Spyglass': { overall: 'tba' },
    'Harry Potter and the Deathly Hallows': { overall: 'tba' },
    'The Road Virus Heads North': { overall: 'tba' },
    'Forever Princess': { overall: 'tba' },
    'Princess Mia': { overall: 'tba' },
    'Princess on the Brink': { overall: 'tba' },
    'Party Princess': { overall: 'tba' },
    'Princess in Training': { overall: 'tba' },
    'Princess in Pink': { overall: 'tba' },
    'Princess in Waiting': { overall: 'tba' },
    'Princess in Love': { overall: 'tba' },
    'Princess in the Spotlight': { overall: 'tba' },
    'I Will Always Love You': { overall: 'tba' },
    "Don't You Forget About Me": { overall: 'tba' },
    'Would I Lie to You': { overall: 'tba' },
    'Only in Your Dreams': { overall: 'tba' },
    'Gossip Girl Boxed Set': { overall: 'tba' },
    'Nothing Can Keep Us Together': { overall: 'tba' },
    'It Had to Be You': { overall: 'tba' },
    'Nobody Does it Better': { overall: 'tba' },
    'I Like It Like That': { overall: 'tba' },
    "Because I'm Worth It": { overall: 'tba' },
    "You're the One That I Want": { overall: 'tba' },
    'All I Want is Everything': { overall: 'tba' },
    'You Know You Love Me': { overall: 'tba' },
    'Gossip Girl': { overall: 'tba' },
    'The Princess Diaries': { overall: 'tba' },
    'Under the Dome': { overall: 'tba' },
    'Der Augensammler': { overall: 'tba' },
    'Die Tochter der Wanderhure': { overall: 'tba' },
    'Das Verm\u00e4chtnis der Wanderhure': { overall: 'tba' },
    'Die Kastellanin': { overall: 'tba' },
    'Die Wanderhure': { overall: 'tba' },
    'Doctor Sleep': { overall: 'tba' },
    Joyland: { overall: 'tba' },
    'Nightmares and Dreamscapes': { overall: 'tba' },
    'The Long Walk': { overall: 'tba' },
    'Duma Key': { overall: 'tba' },
    'The Girl Who Loved Tom Gordon': { overall: 'tba' },
    'The Lost Honor of Katharina Blum': { overall: 'tba' },
    'The Swarm': { overall: 'tba' },
    Mängelexemplar: { overall: 'tba' },
    Woyzeck: { overall: 'tba' },
    'Emil and the Detectives': { overall: 'tba' },
    'Der Sandmann': { overall: 'tba' },
    'Effi Briest': { overall: 'tba' },
    'The Little Witch': { overall: 'tba' },
    'The Little Ghost': { overall: 'tba' },
    'Die Verwandlung': { overall: 'tba' },
    Krabat: { overall: 'tba' },
    'Faust, First Part': { overall: 'tba' },
    Inkheart: { overall: 'tba' },
    'The Neverending Story': { overall: 'tba' },
    'Perfume: The Story of a Murderer': { overall: 'tba' },
    Smaragdgrün: { overall: 'tba' },
    Saphirblau: { overall: 'tba' },
    'Ruby Red': { overall: 'tba' },
    Divergent: { overall: 'tba' },
    Insurgent: { overall: 'tba' },
    Christine: { overall: 'tba' },
    'The High Lord': { overall: 'tba' },
    "The Magicians' Guild": { overall: 'tba' },
    'The Novice': { overall: 'tba' },
    'The Green Mile': { overall: 'tba' },
    '11/22/63': { overall: 'tba' },
    Carrie: { overall: 'tba' },
    It: { overall: 'tba' },
    'The Stand': { overall: 'tba' },
    'The Shining': { overall: 'tba' },
    Graceling: { overall: 'tba' },
    Phantom: { overall: 'tba' },
    Chainfire: { overall: 'tba' },
    'Naked Empire': { overall: 'tba' },
    'Soul of the Fire': { overall: 'tba' },
    'The Pillars of Creation': { overall: 'tba' },
    'Faith of the Fallen': { overall: 'tba' },
    'Temple of the Winds': { overall: 'tba' },
    'Blood of the Fold': { overall: 'tba' },
    'Stone of Tears': { overall: 'tba' },
    "Wizard's First Rule": { overall: 'tba' },
    'Fantastic Beasts and Where to Find Them': { overall: 'tba' },
    'Dragon Rider': { overall: 'tba' },
    'The Golden Compass': { overall: 'tba' },
    Eragon: { overall: 'tba' },
    'Dead in the Family': { overall: 'tba' },
    'Dead and Gone': { overall: 'tba' },
    'From Dead to Worse': { overall: 'tba' },
    'Definitely Dead': { overall: 'tba' },
    'All Together Dead': { overall: 'tba' },
    'Dead as a Doornail': { overall: 'tba' },
    'Club Dead': { overall: 'tba' },
    'Dead to the World': { overall: 'tba' },
    'Living Dead in Dallas': { overall: 'tba' },
    'Dead Until Dark': { overall: 'tba' },
    Twilight: { overall: 'tba' },
    'Wuthering Heights': { overall: 'tba' },
    'The Girl with the Dragon Tattoo': { overall: 'tba' },
    'One Day': { overall: 'tba' },
    "My Sister's Keeper": { overall: 'tba' },
    'Water for Elephants': { overall: 'tba' },
    'Angels & Demons': { overall: 'tba' },
    Room: { overall: 'tba' },
    'The Diary of a Young Girl': { overall: 'tba' },
    'The Picture of Dorian Gray': { overall: 'tba' },
    Persuasion: { overall: 'tba' },
    Emma: { overall: 'tba' },
    'Lord of the Flies': { overall: 'tba' },
    'Romeo and Juliet': { overall: 'tba' },
    'Brave New World': { overall: 'tba' },
    '1984': { overall: 'tba' },
    'Pride and Prejudice': { overall: 'tba' },
    'The Great Gatsby': { overall: 'tba' },
    "Alice's Adventures in Wonderland & Through the Looking-Glass": { overall: 'tba' },
    'Confessions of a Shopaholic': { overall: 'tba' },
    'The Devil Wears Prada': { overall: 'tba' },
    'House of Many Ways': { overall: 'tba' },
    'The Two Towers': { overall: 'tba' },
    'The Return of the King': { overall: 'tba' },
    Momo: { overall: 'tba' },
    'Die Stadt der Tr\u00e4umenden B\u00fccher': { overall: 'tba' },
    "Die 13\u00bd Leben des K\u00e4pt'n Blaub\u00e4r": { overall: 'sun' },
    'The Fellowship of the Ring': { overall: 'tba' },
    'I Am the Messenger': { overall: 'tba' },
    'Das Labyrinth der Tr\u00e4umenden B\u00fccher': { overall: 'tba' },
    'Der eingebildete Kranke': { overall: 'tba' },
    "Alice's Adventures in Wonderland": { overall: 'tba' },
    'Der Schrecksenmeister': { overall: 'tba' },
    'Die Vermessung der Welt': { overall: 'tba' },
    'The Importance of Being Earnest': { overall: 'tba' },
    'Harry Potter and the Prisoner of Azkaban': { overall: 'tba' },
    'Katze mit Hut': { overall: 'tba' },
    "The Hitch Hiker's Guide to the Galaxy: A Trilogy in Five Parts": { overall: 'tba' },
    'Charlie and the Chocolate Factory': { overall: 'tba' },
    'Harry Potter and the Chamber of Secrets': { overall: 'tba' },
    'Catching Fire': { overall: 'tba', loveInterest: 'heart_broken' },
    'Der Duft Des Sake: Roman': { overall: 'tba' },
    Mockingjay: { overall: 'tba' },
    Cthulhu: { overall: 'tba' },
    'The Catcher in the Rye': { overall: 'tba' },
    'Der letzte Wunsch': { overall: 'tba' },
    'The Hunger Games': { overall: 'tba', loveInterest: 'heart_broken' },
    'To Kill a Mockingbird': { overall: 'tba' },
    'The Plays of Oscar Wilde': { overall: 'tba' },
    'The Playbook': { overall: 'tba' },
    'Fight Club': { overall: 'tba' },
    Spiegelzeit: { overall: 'tba' },
    'The Adventures of Sherlock Holmes': { overall: 'tba' },
    'The Bro Code': { overall: 'tba' },
    "Harry Potter and the Philosopher's Stone": { overall: 'tba' },
    'Drehn Sie sich um, Frau Lot. Satiren aus Israel': { overall: 'tba' },
    '1Q84': { overall: 'tba' },
    'Woa\u00dft du ibahapts, wia gern dass i di mog?': { overall: 'tba' },
    'Die Physiker': { overall: 'tba' },
    'Die Kunst des klaren Denkens - 52 Denkfehler, die Sie besser anderen \u00fcberlassen': { overall: 'tba' },
    "Maria, ihm schmeckt's nicht!": { overall: 'tba' },
    'Der kleine Prinz': { overall: 'tba' },
    'A Clash of Kings': { overall: 'tba' },
    'A Game of Thrones': { overall: 'tba' },
    'Marco Effekten': { overall: 'tba' },
    'Journal 64': { overall: 'tba' },
    'Flaskepost fra P': { overall: 'tba' },
    Fasandræberne: { overall: 'tba' },
    'The Keeper of Lost Causes': { overall: 'tba' },
    'City of Bones': { overall: 'tba' },
    'City of Ashes': { overall: 'tba' },
    'City of Glass': { overall: 'tba' },
    'The Host': { overall: 'tba' },
    'Rumo & Die Wunder im Dunkeln': { overall: 'sun', loveInterest: 'heart' },
    "Howl's Moving Castle": { overall: 'sun', loveInterest: 'heart' },
};
